/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-01-15 15:12:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Welcome - Hair & Skincare App</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Reset */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background-image: url(images/indexx.avif); /* Background Image */\r\n");
      out.write("            background-size: cover;  /* Ensures image covers entire page */\r\n");
      out.write("            background-position: center;  /* Centers the image */\r\n");
      out.write("            background-attachment: fixed; /* Makes the background image fixed */\r\n");
      out.write("            \r\n");
      out.write("         /*   background-color: black; /* Pastel cream background */\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("/*         .container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background: #d6eef5; \r\n");
      out.write("            padding: 3rem 4rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0px 8px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            width: 60%; \r\n");
      out.write("            animation: slideIn 1.2s ease-out; \r\n");
      out.write("        } */\r\n");
      out.write("        .container {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: rgba(255, 250, 240, 0.9); /* Pastel cream with slight transparency */\r\n");
      out.write("    padding: 3rem 4rem;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    box-shadow: 0px 8px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    animation: slideIn 0.3s ease-out;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 2.7rem;\r\n");
      out.write("            color: #4b6584; /* Cool dark pastel gray */\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            animation: fadeIn 1.5s ease-in;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            color: #4b6584;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            animation: fadeIn 1.5s ease-in;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column; \r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #ffcccb; /* Pastel pink */\r\n");
      out.write("            color: #4b6584; /* Cool dark pastel gray */\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            width: 110%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            animation: bounce 2s infinite ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #f4a1a1; /* Slightly darker pastel pink */\r\n");
      out.write("            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideIn {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateY(-50%);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes bounce {\r\n");
      out.write("            0%, 100% {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("            50% {\r\n");
      out.write("                transform: translateY(-10px);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Welcome to Personalized Palette</h1>\r\n");
      out.write("        <p>Your journey to glowing skin and healthy hair starts here!</p>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"button-group\">\r\n");
      out.write("            <p>New to Care Craft? Let's get you started:</p>\r\n");
      out.write("            <a href=\"register.jsp\">\r\n");
      out.write("                <button>Register Now</button>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <p>Already have an account? Let's continue:</p>\r\n");
      out.write("            <a href=\"login.jsp\">\r\n");
      out.write("                <button>Login Here</button>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
